---
title: "2019/5/22"
author: '410773015'
date: "2019年5月22日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
now2()
```

```{r}
textbookURL<-function(){
browseURL("https://bookdown.org/tpemartin/ntpu-programming-for-data-science/function-and-conditional-execution.html#section-8.1")}
textbookURL()
```

```{r}
demand_supply_fun <-function(P,a,b,c,d){
  Qs <- a + b*P
  Qd <- c - d*P
  return(
    list(
      供給量=Qs,
      需求量=Qd,
      超額供給量=Qs - Qd
    ) )
}
demand_supply_fun(1,2,3,2,1)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  if(studentID %in% transcriptDataFinal$學號){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  subSample <- transcriptDataFinal[logiChosenStudent,]
  sum(subSample$學期成績*subSample$學分數)/
  sum(subSample$學分數) -> GPA
  return(GPA)}
  else {message("no such ID")}}
gpa_fun("92aS67fee") 
gpa_fun("aa829838s")
```

```{r}
supply_fun4 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P can not be negative") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else if(P < -a/b) {
    message("P must larger than",-a/b,"(-a/b)")
  } else {
    return(Qs)
  }
}
supply_fun4(P=-1,-3,1)
supply_fun4(P=2,-3,1)
supply_fun4(P=3,-3,1)
```


```{r}
6%%3
```

```{r}
fizzbuzz<-function(a){
  if(a%%3==0&a%%5!=0){
    print("ok")
  }
  else if(a%%5==0&a%%3!=0){
    print("kk")
  }
  else if(a%%5==0&a%%3==0){
    print("ko")
  }
  else{
    print("bad")
  }
}
fizzbuzz(3)
fizzbuzz(7)
fizzbuzz(15)
```








