---
title: "2019-05-15 alwin"
author: '410773015'
date: "2019年5月15日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b[[5]]<-"7"
b[[3]]<-"FALSE"
b
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
library(lubridate)
exData3$期間<- ymd(exData3$期間)
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <- ymd("1997-06-01") <= exData3$期間 &
  ymd("1998-12-01") >= exData3$期間
names(exData3)
```

```{r}
exData3[exData3$isAsiaCrisis, ]
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

```{r}
transcriptDataFinal[transcriptDataFinal$學號 == "92aS67fee", ] 
```


```{r}
a <- function(x,.alpha){
  k <- x+.alpha
  return(k)
}
a(1,2)
```

```{r}
供給函數<- function(a,P,b){
  j <- a+b*P
  return(j)
}
需求函數<- function(c,P,d){
  s <- c-d*P
  return(s)
}
```

```{r}
供給函數(1,0,1)
需求函數(1,5,1)
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
gpa_fun("223S63286")
gpa_fun("105S60ba1")
```





